version: '3.7'

#do I need a network here?

volumes:
  db_postgres_data: {}
  pgadmin-data: {}

networks: 
  postgres_network: {}

services: 
  db:
    build: ./db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    ports:
      - "54322:5432"
    expose: 
      - 5432
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    networks: 
      - postgres_network
  
  pgadmin: 
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
    networks: 
      - postgres_network